from tools.github_tool import search_github
from tools.weather_tool import get_weather


def executor_agent(plan: dict) -> list:
    """
    Executes the plan generated by the Planner Agent.
    Calls real tools/APIs and returns structured results.
    """
    results = []

    steps = plan.get("steps", [])

    for step in steps:
        action = step.get("action")
        input_value = step.get("input")

        try:
            if action == "github_search":
                output = search_github(input_value)
                results.append({
                    "tool": "github_search",
                    "result": output
                })

            elif action == "weather":
                output = get_weather(input_value)
                results.append({
                    "tool": "weather",
                    "result": output
                })

            else:
                results.append({
                    "tool": action,
                    "error": "Unsupported tool"
                })

        except Exception as e:
            results.append({
                "tool": action,
                "error": str(e)
            })

    return results